BlackJack/urls.py
"""BlackJack URL Configuration"""

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from GameManager.views import GameManagerLoginView, GameManagerLogoutView, GameManagerRegistrationView, GameCreateView, GameListView, \
    GameListPageView, FastGameCreateView
from BlackJack import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', GameManagerLoginView.as_view(), name='login'),
    path('logout/', GameManagerLogoutView.as_view(), name='logout'),
    path('registration/', GameManagerRegistrationView.as_view(), name='registration'),
    path('games_list/<str:whose>/', GameListView.as_view(), name='game_list'),
    path('games_list/<str:whose>/page/',
         GameListPageView.as_view(), name='game_page'),
    path('game_creation/', GameCreateView.as_view(), name='game_creation'),
    path('fast_game_creation/',
         FastGameCreateView.as_view(success_url='/fast_game_creation/'),
         name='fast_game_creation'),
    path('profile/', include(('GameManager.profile_urls', 'P'))),
    path('<int:id>/', include(('GameManager.game_urls', 'GameManager'))),
    path('', GameManagerLoginView.as_view(), name='login'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

GameManager/models.py
from django.core import validators
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from GameManager.tools import modify_fields


@modify_fields(
    username={
        'verbose_name': 'Имя пользователя',
        'help_text': 'Уникальное имя - логин',
        'error_messages': {'unique': 'Данное имя уже занято'},
        # I am lazy to handle the remaining messages
        # TODO: Handle all error_messages
    },
)
class Profile(AbstractUser):

    AbstractUser._meta.get_field('username').validators = [
        validators.MinLengthValidator(2)]
    AbstractUser._meta.get_field('password').verbose_name = 'Пароль'

    avatar = models.ImageField(
        upload_to='avatars/',
        blank=True,
        null=True,
        default='avatars/default_avatar.png',
        verbose_name='Аватар'
    )
    description = models.CharField(
        max_length=255,
        verbose_name='О себе',
        blank=True,
        null=True
    )
    objects = UserManager()

    class Meta:
        db_table = 'users'
        verbose_name = _('Профиль пользователя')
        verbose_name_plural = _('Профили пользователей')


class Game(models.Model):
    name = models.CharField(max_length=80, verbose_name='Игра')
    description = models.TextField(max_length=4096, verbose_name='Описание')
    owner = models.ManyToManyField(Profile, verbose_name='Владелец')
    platform = models.IntegerField(choices=settings.PLATFORMS,
                                   null=True,
                                   verbose_name='Платформа')
    game_image = models.ImageField(upload_to='game_images/', blank=True, null=True,
                                   default='game_images/default_game_image.png',
                                   verbose_name='Изображение')

    class Meta:
        db_table = 'game'
        verbose_name = _('Игра')
        verbose_name_plural = _('Игры')

templates/game_list/game/game.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ game.name }} {% endblock %}
{% block extrastyles %}
<link rel="stylesheet" type="text/css" href="{% static "/css/game.css" %}">
<link rel="stylesheet" type="text/css" href="{% static "/css/menu.css" %}">
{% endblock %}
{% block content %}
{% include 'menu.html' with user=user %}
<div class="game">
    <div class='game_image_full' style="background: url('/media/{{game.game_image}}') no-repeat center;
                             background-size: contain;">
    </div><br><br>
    <div class="description">
        <table>
            <tr>
                <td>Игра:</td>
                <td>{{game.name}}</td>
            </tr>
            <tr>
                <td>Описание:</td>
                <td>{{ game.description }}</td>
            </tr>
            <tr>
                <td>Платформа:</td>
                <td>{{ game.get_platform_display }}</td>
            </tr>
        </table>
    </div>
</div>
<div class=action_bar>
    {% if is_owner %}
    {% if last_owner %}
    <form action="{% url 'GameManager:game_remove' game.id%}">
        <div class="space">
            <button type="submit" class="btn btn-primary">Удалить игру</button>
        </div>
    </form>
    {% else %}
    <form action="{% url 'GameManager:game_leave' game.id%}">
        <div class="space">
            <button type="submit" class="btn btn-primary">Удалить из своей коллекции</button>
        </div>
    </form>
    {% endif %}
    {% else %}
    <form action="{% url 'GameManager:game_join' game.id%}">
        <div class="space">
            <button type="submit" class="btn btn-primary">Добавить к себе в коллекцию</button>
        </div>
    </form>
    {% endif %}
</div>
{% endblock %}